language: r
before_install:
- cd dbl
sudo: false
cache: packages
script:
- make download
- make commit_input_files
- make push_changes
env:
  global:
    secure: cCMUjOlG1+9CJt4yQ5LYIpEv67ERvetTvk5nnf5WP1/k1jvfvaPuhK7zVA5tLNROfY9uChwYfGHNOzl1H+t4VpUZUt4EyZ4UjJQ43pTiEfArOwACtzVQBES1IQzth74hvk4LNTQzJ8kXJLBDKMc70a4ubVHh6EtN8+cvi7tf8gA=
