language: r
before_install:
- cd dbl
sudo: false
cache: packages
script:
- make travis_checkout_branch
- make prepare
- make process
- make commit_input_files
- make commit_report_files
- make travis_push
- make travis_make_site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: "site/blog/html"
  on:
    branch: master
env:
  global:
    - SEASON='2018-2019'
    - secure: pHUjzASSHrKlJavb5+ih5vKFd6qtE+Lo3Q8qeh5hZslm+7rzHdx6JkzhE16e+0BQSKLYrI184e/0NCCFy/9cB7kOQRgUJ+LzrAHyxheWJpz+C1aSMQbttPQCm8g+2y2ZH8qk5Q2Rp/pa7II1tqlOg0nJVRqGIiNpUKuUu1o+n0I=
