language: r
before_install:
- python --version
- pyenv versions
- pyenv global 3.6.3
- python --version
- pip --version
- cd dbl
sudo: false
cache: packages
script:
- make prepare
- make process
- make travis_checkout_branch
- make commit_input_files
- make commit_report_files
- make travis_push
env:
  global:
    - SEASON='2018-2019'
    - secure: pHUjzASSHrKlJavb5+ih5vKFd6qtE+Lo3Q8qeh5hZslm+7rzHdx6JkzhE16e+0BQSKLYrI184e/0NCCFy/9cB7kOQRgUJ+LzrAHyxheWJpz+C1aSMQbttPQCm8g+2y2ZH8qk5Q2Rp/pa7II1tqlOg0nJVRqGIiNpUKuUu1o+n0I=
